idle_bg = "#282c34"
idle_fg = "#abb2bf"
info_bg = "#61afef"
info_fg = "#282c34"
good_bg = "#282c34"
good_fg = "#abb2bf"
warning_bg = "#e5c07b"
warning_fg = "#282c34"
critical_bg = "#e06c75"
critical_fg = "#282c34"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#282c34"
alternating_tint_fg = "#abb2bf"
